aureservoir::ESN
friend class InitBase< T >
friend class InitStd< T >
friend class TrainBase< T >
friend class TrainPI< T >
friend class TrainLS< T >
friend class TrainRidgeReg< T >
friend class TrainDSPI< T >
friend class SimBase< T >
friend class SimStd< T >
friend class SimSquare< T >
friend class SimLI< T >
friend class SimBP< T >
friend class SimFilter< T >
friend class SimFilter2< T >
friend class SimFilterDS< T >
void aureservoir::ESN< T >::init()
Initialization Algorithm for an Echo State Network class InitBase
References aureservoir::ESN< T >::init_.
Referenced by aureservoir::ESN< T >::operator=.
double aureservoir::ESN< T >::adapt(const DEMatrix &in)
Reservoir Adaptation Algorithm Interface At the moment this is only the Gaussian-IP reservoir adaptation method for tanh neurons. "Adapting reservoirs to get Gaussian distributions" by David Verstraeten, Benjamin Schrauwen and Dirk Stroobandt in matrix of input values (inputs x timesteps), the reservoir will be adapted by this number of timesteps. mean value of differences between all parameters before and after adaptation, can be used to see if learning still makes an progress.
References aureservoir::ACT_LINEAR, aureservoir::act_tanh2, aureservoir::ACT_TANH2, aureservoir::ESN< T >::init_params_, aureservoir::ESN< T >::inputs_, aureservoir::IP_LEARNRATE, aureservoir::IP_MEAN, aureservoir::IP_VAR, aureservoir::ESN< T >::net_info_, aureservoir::ESN< T >::neurons_, aureservoir::ESN< T >::outputs_, aureservoir::ESN< T >::RESERVOIR_ACT, aureservoir::ESN< T >::setReservoirAct, aureservoir::ESN< T >::simulate, aureservoir::tanh2_a_, aureservoir::tanh2_b_, aureservoir::ESN< T >::x_.
Referenced by aureservoir::ESN< T >::adapt.
void aureservoir::ESN< T >::train(const DEMatrix &in, const DEMatrix &out, int washout)
Training Algorithm Interface class TrainBase in matrix of input values (inputs x timesteps) out matrix of desired output values (outputs x timesteps) for teacher forcing washout washout time in samples, used to get rid of the transient dynamics of the network starting state
References aureservoir::DS_MAXDELAY, aureservoir::ESN< T >::getDelays, aureservoir::ESN< T >::init_params_, aureservoir::ESN< T >::inputs_, aureservoir::ESN< T >::outputs_, aureservoir::RELAXATION_STAGES, aureservoir::ESN< T >::sim_, aureservoir::ESN< T >::simulate, aureservoir::ESN< T >::train_.
Referenced by aureservoir::ESN< T >::operator=, aureservoir::ESN< T >::train.
void aureservoir::ESN< T >::simulate(const DEMatrix &in, DEMatrix &out)
Simulation Algorithm Interface class SimBase in matrix of input values (inputs x timesteps) out matrix for output values (outputs x timesteps)
References aureservoir::ESN< T >::sim_.
Referenced by aureservoir::ESN< T >::adapt, aureservoir::ESN< T >::simulate, aureservoir::ESN< T >::simulateStep, aureservoir::ESN< T >::teacherForce, aureservoir::ESN< T >::train.
void aureservoir::ESN< T >::teacherForce(const DEMatrix &in, DEMatrix &out)
Teacher Forcing a input and target signal without learning output weights. This is useful for ESNs in generator mode to initialize the internal state. in matrix of input values (inputs x timesteps) out matrix for output values (outputs x timesteps)
References aureservoir::ESN< T >::inputs_, aureservoir::ESN< T >::outputs_, aureservoir::ESN< T >::sim_, aureservoir::ESN< T >::simulate.
Referenced by aureservoir::ESN< T >::teacherForce.
void aureservoir::ESN< T >::resetState()
resets the internal state vector x of the reservoir to zero
References aureservoir::ESN< T >::outputs_, aureservoir::ESN< T >::sim_, aureservoir::ESN< T >::x_.
double aureservoir::ESN< T >::adapt(T *inmtx, int inrows, int incols)
C-style Reservoir Adaptation Algorithm Interface (data will be copied into a FLENS matrix) At the moment this is only the Gaussian-IP reservoir adaptation method for tanh neurons. "Adapting reservoirs to get Gaussian distributions" by David Verstraeten, Benjamin Schrauwen and Dirk Stroobandt inmtx matrix of input values (inputs x timesteps), the reservoir will be adapted by this number of timesteps. mean value of differences between all parameters before and after adaptation, can be used to see if learning still makes an progress.
References aureservoir::ESN< T >::adapt, aureservoir::ESN< T >::inputs_.
void aureservoir::ESN< T >::train(T *inmtx, int inrows, int incols, T *outmtx, int outrows, int outcols, int washout)
C-style Training Algorithm Interface (data will be copied into a FLENS matrix) class TrainBase inmtx input matrix in row major storage (usual C array) (inputs x timesteps) outmtx output matrix in row major storage (outputs x timesteps) for teacher forcing washout washout time in samples, used to get rid of the transient dynamics of the network starting state
References aureservoir::ESN< T >::train.
void aureservoir::ESN< T >::simulate(T *inmtx, int inrows, int incols, T *outmtx, int outrows, int outcols)
C-style Simulation Algorithm Interface with some additional error checking. (data will be copied into a FLENS matrix) class SimBase inmtx input matrix in row major storage (usual C array) (inputs x timesteps) outmtx output matrix in row major storage (outputs x timesteps), Data must be already allocated!
References aureservoir::ESN< T >::inputs_, aureservoir::ESN< T >::outputs_, aureservoir::ESN< T >::sim_, aureservoir::ESN< T >::simulate.
void aureservoir::ESN< T >::simulateStep(T *invec, int insize, T *outvec, int outsize)
C-style Simulation Algorithm Interface, for single step simulation class SimBase inmtx input vector, size = inputs outmtx output vector, size = outputs Data must be already allocated!
References aureservoir::ESN< T >::inputs_, aureservoir::ESN< T >::outputs_, aureservoir::ESN< T >::sim_, aureservoir::ESN< T >::simulate.
void aureservoir::ESN< T >::teacherForce(T *inmtx, int inrows, int incols, T *outmtx, int outrows, int outcols)
Teacher Forcing a input and target signal without learning output weights. This is useful for ESNs in generator mode to initialize the internal state. inmtx input matrix in row major storage (usual C array) (inputs x timesteps) outmtx output matrix in row major storage (outputs x timesteps) for teacher forcing
References aureservoir::ESN< T >::teacherForce.
void aureservoir::ESN< T >::setBPCutoff(const DEVector &f1, const DEVector &f2)
Set lowpass/highpass cutoff frequencies for bandpass style neurons. " class SimBP f1 vector with lowpass cutoff for all neurons (size = neurons) f2 vector with highpass cutoffs (size = neurons)
References aureservoir::ESN< T >::net_info_, aureservoir::ESN< T >::sim_, aureservoir::SIM_BP, aureservoir::ESN< T >::SIMULATE_ALG.
Referenced by aureservoir::ESN< T >::setBPCutoff.
void aureservoir::ESN< T >::setBPCutoff(T *f1vec, int f1size, T *f2vec, int f2size)
Set lowpass/highpass cutoff frequencies for bandpass style neurons " (C-style Interface). f1 vector with lowpass cutoff for all neurons (size = neurons) f2 vector with highpass cutoffs (size = neurons)
References aureservoir::ESN< T >::neurons_, aureservoir::ESN< T >::setBPCutoff.
void aureservoir::ESN< T >::setIIRCoeff(const DEMatrix &B, const DEMatrix &A, int series=1)
sets the IIR-Filter coefficients, like Matlabs filter object. B matrix with numerator coefficient vectors (m x nb) m ... nr of parallel filters (neurons) nb ... nr of filter coefficients A matrix with denominator coefficient vectors (m x na) m ... nr of parallel filters (neurons) na ... nr of filter coefficients seris nr of serial IIR filters, e.g. if series=2 the coefficients B and A will be divided in its half and calculated with 2 serial IIR filters
References aureservoir::ESN< T >::net_info_, aureservoir::ESN< T >::sim_, aureservoir::SIM_FILTER, aureservoir::SIM_FILTER2, aureservoir::SIM_FILTER_DS, aureservoir::SIM_SQUARE, aureservoir::ESN< T >::SIMULATE_ALG.
void aureservoir::ESN< T >::setIIRCoeff(T *bmtx, int brows, int bcols, T *amtx, int arows, int acols, int series=1)
sets the IIR-Filter coefficients, like Matlabs filter object. B matrix with numerator coefficient vectors (m x nb) m ... nr of parallel filters (neurons) nb ... nr of filter coefficients A matrix with denominator coefficient vectors (m x na) m ... nr of parallel filters (neurons) na ... nr of filter coefficients seris nr of serial IIR filters, e.g. if series=2 the coefficients B and A will be divided in its half and calculated with 2 serial IIR filters
References aureservoir::ESN< T >::neurons_, aureservoir::ESN< T >::sim_.
void aureservoir::ESN< T >::post()
posts current parameters to stdout
References aureservoir::ALPHA, aureservoir::CONNECTIVITY, aureservoir::FB_CONNECTIVITY, aureservoir::FB_SCALE, aureservoir::FB_SHIFT, aureservoir::ESN< T >::getActString, aureservoir::ESN< T >::getInitString, aureservoir::ESN< T >::getSimString, aureservoir::ESN< T >::getTrainString, aureservoir::IN_CONNECTIVITY, aureservoir::IN_SCALE, aureservoir::IN_SHIFT, aureservoir::ESN< T >::INIT_ALG, aureservoir::ESN< T >::init_params_, aureservoir::ESN< T >::inputs_, aureservoir::LEAKING_RATE, aureservoir::ESN< T >::net_info_, aureservoir::ESN< T >::neurons_, aureservoir::ESN< T >::noise_, aureservoir::ESN< T >::OUTPUT_ACT, aureservoir::ESN< T >::outputs_, aureservoir::ESN< T >::RESERVOIR_ACT, aureservoir::SIM_LI, aureservoir::ESN< T >::SIMULATE_ALG, aureservoir::ESN< T >::TRAIN_ALG.
int aureservoir::ESN< T >::getSize() const
reservoir size (nr of neurons)
References aureservoir::ESN< T >::neurons_.
int aureservoir::ESN< T >::getInputs() const
nr of inputs to the reservoir
References aureservoir::ESN< T >::inputs_.
int aureservoir::ESN< T >::getOutputs() const
nr of outputs from the reservoir
References aureservoir::ESN< T >::outputs_.
double aureservoir::ESN< T >::getNoise() const
current noise level
References aureservoir::ESN< T >::noise_.
T aureservoir::ESN< T >::getInitParam(InitParameter key)
returns an initialization parametern from the parameter map key the requested parameter the value of the parameter
References aureservoir::ESN< T >::init_params_.
InitAlgorithm aureservoir::ESN< T >::getInitAlgorithm() const
initialization algorithm
References aureservoir::ESN< T >::INIT_ALG, aureservoir::ESN< T >::net_info_.
Referenced by aureservoir::ESN< T >::operator=.
TrainAlgorithm aureservoir::ESN< T >::getTrainAlgorithm() const
training algorithm
References aureservoir::ESN< T >::net_info_, aureservoir::ESN< T >::TRAIN_ALG.
Referenced by aureservoir::ESN< T >::operator=.
SimAlgorithm aureservoir::ESN< T >::getSimAlgorithm() const
simulation algorithm
References aureservoir::ESN< T >::net_info_, aureservoir::ESN< T >::SIMULATE_ALG.
Referenced by aureservoir::ESN< T >::operator=.
ActivationFunction aureservoir::ESN< T >::getReservoirAct() const
reservoir activation function
References aureservoir::ESN< T >::net_info_, aureservoir::ESN< T >::RESERVOIR_ACT.
Referenced by aureservoir::ESN< T >::operator=.
ActivationFunction aureservoir::ESN< T >::getOutputAct() const
output activation function
References aureservoir::ESN< T >::net_info_, aureservoir::ESN< T >::OUTPUT_ACT.
Referenced by aureservoir::ESN< T >::operator=.
const DEMatrix& aureservoir::ESN< T >::getWin()
input weight matrix (neurons x inputs)
References aureservoir::ESN< T >::Win_.
const SPMatrix& aureservoir::ESN< T >::getW()
reservoir weight matrix (neurons x neurons)
References aureservoir::ESN< T >::W_.
const DEMatrix& aureservoir::ESN< T >::getWback()
feedback (output to reservoir) weight matrix (neurons x outputs)
References aureservoir::ESN< T >::Wback_.
const DEMatrix& aureservoir::ESN< T >::getWout()
output weight matrix (outputs x neurons+inputs)
References aureservoir::ESN< T >::Wout_.
const DEVector& aureservoir::ESN< T >::getX()
internal state vector x (size = neurons)
References aureservoir::ESN< T >::x_.
DEMatrix aureservoir::ESN< T >::getDelays()
query the trained delays in delay&sum readout class SimFilterDS matrix with delay form neurons+inputs to all outputs size = (output x neurons+inputs)
References aureservoir::ESN< T >::sim_.
Referenced by aureservoir::ESN< T >::getDelays, aureservoir::ESN< T >::train.
DEMatrix aureservoir::ESN< T >::getReservoirDelays()
query the (fixed) delays between reservoir neurons class SimFilterDS matrix with delays between all reservoir neurons size = (neurons x neurons)
References aureservoir::ESN< T >::sim_.
Referenced by aureservoir::ESN< T >::getReservoirDelays.
void aureservoir::ESN< T >::getWin(T **mtx, int *rows, int *cols)
get pointer to input weight matrix data and dimensions (neurons x inputs) This data is in fortran style column major storage !
References aureservoir::ESN< T >::Win_.
void aureservoir::ESN< T >::getWback(T **mtx, int *rows, int *cols)
get pointer to feedback weight matrix data and dimensions (neurons x outputs) This data is in fortran style column major storage !
References aureservoir::ESN< T >::Wback_.
void aureservoir::ESN< T >::getWout(T **mtx, int *rows, int *cols)
get pointer to output weight matrix data and dimensions (outputs x neurons+inputs) This data is in fortran style column major storage !
References aureservoir::ESN< T >::Wout_.
void aureservoir::ESN< T >::getX(T **vec, int *length)
get pointer to internal state vector x data and length
References aureservoir::ESN< T >::x_.
void aureservoir::ESN< T >::getW(T *wmtx, int wrows, int wcols)
Copies data of the sparse reservoir weight matrix into a dense C-style matrix. Memory of the C array must be allocated before! wmtx pointer to matrix of size (neurons_ x neurons_)
References aureservoir::ESN< T >::W_.
void aureservoir::ESN< T >::getDelays(T *wmtx, int wrows, int wcols)
query the trained delays in delay&sum readout class SimFilterDS and copies the data into a C-style matrix Memory of the C array must be allocated before! wmtx matrix with delay form neurons+inputs to all outputs size = (output x neurons+inputs)
References aureservoir::ESN< T >::getDelays.
void aureservoir::ESN< T >::getReservoirDelays(T *wmtx, int wrows, int wcols)
query the (fixed) delays between reservoir neurons class SimFilterDS and copies the data into a C-style matrix Memory of the C array must be allocated before! wmtx matrix with delays between all reservoir neurons size = (neurons x neurons)
References aureservoir::ESN< T >::getReservoirDelays.
void aureservoir::ESN< T >::setInitAlgorithm(InitAlgorithm alg=INIT_STD)
set initialization algorithm
References aureservoir::ESN< T >::init_, aureservoir::ESN< T >::INIT_ALG, aureservoir::INIT_STD, aureservoir::ESN< T >::net_info_.
Referenced by aureservoir::ESN< T >::ESN, aureservoir::ESN< T >::operator=.
void aureservoir::ESN< T >::setTrainAlgorithm(TrainAlgorithm alg=TRAIN_PI)
set training algorithm
References aureservoir::ESN< T >::net_info_, aureservoir::ESN< T >::train_, aureservoir::ESN< T >::TRAIN_ALG, aureservoir::TRAIN_DS_PI, aureservoir::TRAIN_LS, aureservoir::TRAIN_PI, aureservoir::TRAIN_RIDGEREG.
Referenced by aureservoir::ESN< T >::ESN, aureservoir::ESN< T >::operator=.
void aureservoir::ESN< T >::setSimAlgorithm(SimAlgorithm alg=SIM_STD)
set simulation algorithm
References aureservoir::ESN< T >::net_info_, aureservoir::ESN< T >::sim_, aureservoir::SIM_BP, aureservoir::SIM_FILTER, aureservoir::SIM_FILTER2, aureservoir::SIM_FILTER_DS, aureservoir::SIM_LI, aureservoir::SIM_SQUARE, aureservoir::SIM_STD, aureservoir::ESN< T >::SIMULATE_ALG.
Referenced by aureservoir::ESN< T >::ESN.
void aureservoir::ESN< T >::setSize(int neurons=10)
set reservoir size (nr of neurons)
References aureservoir::ESN< T >::neurons_.
Referenced by aureservoir::ESN< T >::ESN.
void aureservoir::ESN< T >::setInputs(int inputs=1)
set nr of inputs to the reservoir
References aureservoir::ESN< T >::inputs_.
Referenced by aureservoir::ESN< T >::ESN.
void aureservoir::ESN< T >::setOutputs(int outputs=1)
set nr of outputs from the reservoir
References aureservoir::ESN< T >::outputs_.
Referenced by aureservoir::ESN< T >::ESN.
void aureservoir::ESN< T >::setNoise(double noise)
set noise level for training/simulation algorithm noise with uniform distribution within [-noise|+noise]
References aureservoir::ESN< T >::noise_.
void aureservoir::ESN< T >::setInitParam(InitParameter key, T value=0.)
set initialization parameter
References aureservoir::ESN< T >::init_params_.
Referenced by aureservoir::ESN< T >::ESN.
void aureservoir::ESN< T >::setReservoirAct(ActivationFunction f=ACT_TANH)
set reservoir activation function
References aureservoir::act_linear, aureservoir::ACT_LINEAR, aureservoir::act_sigmoid, aureservoir::ACT_SIGMOID, aureservoir::act_tanh, aureservoir::ACT_TANH, aureservoir::act_tanh2, aureservoir::ACT_TANH2, aureservoir::ESN< T >::net_info_, aureservoir::ESN< T >::RESERVOIR_ACT, aureservoir::ESN< T >::reservoirAct_.
Referenced by aureservoir::ESN< T >::adapt, aureservoir::ESN< T >::ESN, aureservoir::ESN< T >::operator=.
void aureservoir::ESN< T >::setOutputAct(ActivationFunction f=ACT_LINEAR)
set output activation function
References aureservoir::act_invlinear, aureservoir::act_invsigmoid, aureservoir::act_invtanh, aureservoir::act_linear, aureservoir::ACT_LINEAR, aureservoir::act_sigmoid, aureservoir::ACT_SIGMOID, aureservoir::act_tanh, aureservoir::ACT_TANH, aureservoir::ESN< T >::net_info_, aureservoir::ESN< T >::OUTPUT_ACT, aureservoir::ESN< T >::outputAct_, aureservoir::ESN< T >::outputInvAct_.
Referenced by aureservoir::ESN< T >::ESN, aureservoir::ESN< T >::operator=.
void aureservoir::ESN< T >::setWin(const DEMatrix &Win)
set input weight matrix (neurons x inputs)
References aureservoir::ESN< T >::inputs_, aureservoir::ESN< T >::neurons_, aureservoir::ESN< T >::Win_.
void aureservoir::ESN< T >::setW(const DEMatrix &W)
set reservoir weight matrix (neurons x neurons)
References aureservoir::ESN< T >::neurons_, aureservoir::ESN< T >::W_.
void aureservoir::ESN< T >::setWback(const DEMatrix &Wback)
set feedback weight matrix (neurons x outputs)
References aureservoir::ESN< T >::neurons_, aureservoir::ESN< T >::outputs_, aureservoir::ESN< T >::Wback_.
void aureservoir::ESN< T >::setWout(const DEMatrix &Wout)
set output weight matrix (outputs x neurons+inputs)
References aureservoir::ESN< T >::inputs_, aureservoir::ESN< T >::neurons_, aureservoir::ESN< T >::outputs_, aureservoir::ESN< T >::Wout_.
void aureservoir::ESN< T >::setX(const DEVector &x)
set internal state vector (size = neurons)
References aureservoir::ESN< T >::neurons_, aureservoir::ESN< T >::x_.
void aureservoir::ESN< T >::setLastOutput(const DEVector &last)
set last output, stored by the simulation algorithm needed in singleStep simulation with feedback last vector with length = outputs
References aureservoir::ESN< T >::outputs_, aureservoir::ESN< T >::sim_.
void aureservoir::ESN< T >::setWin(T *inmtx, int inrows, int incols)
set input weight matrix C-style interface (neurons x inputs) (data will be copied into a FLENS matrix) inmtx pointer to win matrix in row major storage
References aureservoir::ESN< T >::inputs_, aureservoir::ESN< T >::neurons_, aureservoir::ESN< T >::Win_.
void aureservoir::ESN< T >::setW(T *inmtx, int inrows, int incols)
set reservoir weight matrix C-style interface (neurons x neurons) (data will be copied into a FLENS matrix) inmtx pointer to a dense reservoir matrix in row major storage
References aureservoir::ESN< T >::neurons_, aureservoir::ESN< T >::W_.
void aureservoir::ESN< T >::setWback(T *inmtx, int inrows, int incols)
set feedback weight matrix C-style interface (neurons x outputs) (data will be copied into a FLENS matrix) inmtx pointer to wback matrix in row major storage
References aureservoir::ESN< T >::neurons_, aureservoir::ESN< T >::outputs_, aureservoir::ESN< T >::Wback_.
void aureservoir::ESN< T >::setWout(T *inmtx, int inrows, int incols)
set output weight matrix C-style interface (outputs x neurons+inputs) (data will be copied into a FLENS matrix) inmtx pointer to wout matrix in row major storage
References aureservoir::ESN< T >::inputs_, aureservoir::ESN< T >::neurons_, aureservoir::ESN< T >::outputs_, aureservoir::ESN< T >::Wout_.
void aureservoir::ESN< T >::setX(T *invec, int insize)
set internal state vector C-style interface (size = neurons) (data will be copied into a FLENS matrix) invec pointer to state vector
References aureservoir::ESN< T >::neurons_, aureservoir::ESN< T >::x_.
void aureservoir::ESN< T >::setLastOutput(T *last, int size)
set last output, stored by the simulation algorithm needed in singleStep simulation with feedback last vector with size = outputs
References aureservoir::ESN< T >::outputs_, aureservoir::ESN< T >::sim_.
NetInfo
reservoir activation function
typedef std::map<NetInfo, int> aureservoir::ESN< T >::InfoMap
typedef std::map<InitParameter,T> aureservoir::ESN< T >::ParameterMap
typedef of a Parameter Map
typedef SPMatrix<T>::Type aureservoir::ESN< T >::SPMatrix
typedef DEMatrix<T>::Type aureservoir::ESN< T >::DEMatrix
typedef DEVector<T>::Type aureservoir::ESN< T >::DEVector
InitBase<T>* aureservoir::ESN< T >::init_
function object for initialization algorithm
Referenced by aureservoir::ESN< T >::ESN, aureservoir::ESN< T >::init, aureservoir::ESN< T >::operator=, aureservoir::ESN< T >::setInitAlgorithm, aureservoir::ESN< T >::~ESN.
TrainBase<T>* aureservoir::ESN< T >::train_
function object for training algorithm
Referenced by aureservoir::ESN< T >::ESN, aureservoir::ESN< T >::operator=, aureservoir::ESN< T >::setTrainAlgorithm, aureservoir::ESN< T >::train, aureservoir::ESN< T >::~ESN.
SimBase<T>* aureservoir::ESN< T >::sim_
function object for simulation algorithm
Referenced by aureservoir::ESN< T >::ESN, aureservoir::ESN< T >::getDelays, aureservoir::ESN< T >::getReservoirDelays, aureservoir::ESN< T >::operator=, aureservoir::ESN< T >::resetState, aureservoir::ESN< T >::setBPCutoff, aureservoir::ESN< T >::setIIRCoeff, aureservoir::ESN< T >::setLastOutput, aureservoir::ESN< T >::setSimAlgorithm, aureservoir::ESN< T >::simulate, aureservoir::ESN< T >::simulateStep, aureservoir::ESN< T >::teacherForce, aureservoir::ESN< T >::train, aureservoir::ESN< T >::~ESN.
DEMatrix aureservoir::ESN< T >::Win_
input weight matrix
Referenced by aureservoir::ESN< T >::getWin, aureservoir::ESN< T >::operator=, aureservoir::ESN< T >::setWin.
SPMatrix aureservoir::ESN< T >::W_
reservoir weight matrix
Referenced by aureservoir::ESN< T >::getW, aureservoir::ESN< T >::operator=, aureservoir::ESN< T >::setW.
DEMatrix aureservoir::ESN< T >::Wback_
feedback (output to reservoir) weight matrix
Referenced by aureservoir::ESN< T >::getWback, aureservoir::ESN< T >::operator=, aureservoir::ESN< T >::setWback.
DEMatrix aureservoir::ESN< T >::Wout_
output weight matrix (this will be trained)
Referenced by aureservoir::ESN< T >::getWout, aureservoir::ESN< T >::operator=, aureservoir::ESN< T >::setWout.
DEVector aureservoir::ESN< T >::x_
internal state vector holding the current value of each neuron in the reservoir
Referenced by aureservoir::ESN< T >::adapt, aureservoir::ESN< T >::getX, aureservoir::ESN< T >::operator=, aureservoir::ESN< T >::resetState, aureservoir::ESN< T >::setX.
void(* aureservoir::ESN< T >::reservoirAct_)(T *data, int size))(T *data, int size)
activation function for the reservoir activations.h
Referenced by aureservoir::ESN< T >::setReservoirAct.
void(* aureservoir::ESN< T >::outputAct_)(T *data, int size))(T *data, int size)
activation function for the outputs activations.h
Referenced by aureservoir::ESN< T >::setOutputAct.
void(* aureservoir::ESN< T >::outputInvAct_)(T *data, int size))(T *data, int size)
inverse activation function for the outputs activations.h
Referenced by aureservoir::ESN< T >::setOutputAct.
int aureservoir::ESN< T >::neurons_
nr of neurons in the reservoir (= reservoir size)
Referenced by aureservoir::ESN< T >::adapt, aureservoir::ESN< T >::getSize, aureservoir::ESN< T >::operator=, aureservoir::ESN< T >::post, aureservoir::ESN< T >::setBPCutoff, aureservoir::ESN< T >::setIIRCoeff, aureservoir::ESN< T >::setSize, aureservoir::ESN< T >::setW, aureservoir::ESN< T >::setWback, aureservoir::ESN< T >::setWin, aureservoir::ESN< T >::setWout, aureservoir::ESN< T >::setX.
int aureservoir::ESN< T >::inputs_
nr of inputs to the reservoir
Referenced by aureservoir::ESN< T >::adapt, aureservoir::ESN< T >::getInputs, aureservoir::ESN< T >::operator=, aureservoir::ESN< T >::post, aureservoir::ESN< T >::setInputs, aureservoir::ESN< T >::setWin, aureservoir::ESN< T >::setWout, aureservoir::ESN< T >::simulate, aureservoir::ESN< T >::simulateStep, aureservoir::ESN< T >::teacherForce, aureservoir::ESN< T >::train.
int aureservoir::ESN< T >::outputs_
nr of outputs from the reservoir
Referenced by aureservoir::ESN< T >::adapt, aureservoir::ESN< T >::getOutputs, aureservoir::ESN< T >::operator=, aureservoir::ESN< T >::post, aureservoir::ESN< T >::resetState, aureservoir::ESN< T >::setLastOutput, aureservoir::ESN< T >::setOutputs, aureservoir::ESN< T >::setWback, aureservoir::ESN< T >::setWout, aureservoir::ESN< T >::simulate, aureservoir::ESN< T >::simulateStep, aureservoir::ESN< T >::teacherForce, aureservoir::ESN< T >::train.
double aureservoir::ESN< T >::noise_
noise level
Referenced by aureservoir::ESN< T >::ESN, aureservoir::ESN< T >::getNoise, aureservoir::ESN< T >::operator=, aureservoir::ESN< T >::post, aureservoir::ESN< T >::setNoise.
ParameterMap aureservoir::ESN< T >::init_params_
parameter map for initialization arguments
Referenced by aureservoir::ESN< T >::adapt, aureservoir::ESN< T >::getInitParam, aureservoir::ESN< T >::operator=, aureservoir::ESN< T >::post, aureservoir::ESN< T >::setInitParam, aureservoir::ESN< T >::train.
InfoMap aureservoir::ESN< T >::net_info_
holds strings of various ESN settings
Referenced by aureservoir::ESN< T >::adapt, aureservoir::ESN< T >::getInitAlgorithm, aureservoir::ESN< T >::getOutputAct, aureservoir::ESN< T >::getReservoirAct, aureservoir::ESN< T >::getSimAlgorithm, aureservoir::ESN< T >::getTrainAlgorithm, aureservoir::ESN< T >::operator=, aureservoir::ESN< T >::post, aureservoir::ESN< T >::setBPCutoff, aureservoir::ESN< T >::setIIRCoeff, aureservoir::ESN< T >::setInitAlgorithm, aureservoir::ESN< T >::setOutputAct, aureservoir::ESN< T >::setReservoirAct, aureservoir::ESN< T >::setSimAlgorithm, aureservoir::ESN< T >::setTrainAlgorithm.
aureservoir::ESN< T >::ESN()
Constructor.
References aureservoir::ACT_LINEAR, aureservoir::ACT_TANH, aureservoir::ALPHA, aureservoir::CONNECTIVITY, aureservoir::FB_CONNECTIVITY, aureservoir::FB_SCALE, aureservoir::FB_SHIFT, aureservoir::IN_CONNECTIVITY, aureservoir::IN_SCALE, aureservoir::IN_SHIFT, aureservoir::ESN< T >::init_, aureservoir::INIT_STD, aureservoir::ESN< T >::noise_, aureservoir::set_denormal_flags, aureservoir::ESN< T >::setInitAlgorithm, aureservoir::ESN< T >::setInitParam, aureservoir::ESN< T >::setInputs, aureservoir::ESN< T >::setOutputAct, aureservoir::ESN< T >::setOutputs, aureservoir::ESN< T >::setReservoirAct, aureservoir::ESN< T >::setSimAlgorithm, aureservoir::ESN< T >::setSize, aureservoir::ESN< T >::setTrainAlgorithm, aureservoir::ESN< T >::sim_, aureservoir::SIM_STD, aureservoir::ESN< T >::train_, aureservoir::TRAIN_PI.
aureservoir::ESN< T >::ESN(const ESN< T > &src)
Copy Constructor.
References aureservoir::ESN< T >::operator=.
ESN< T > & aureservoir::ESN< T >::operator=(const ESN< T > &src)
assignement operator
References aureservoir::ESN< T >::getInitAlgorithm, aureservoir::ESN< T >::getOutputAct, aureservoir::ESN< T >::getReservoirAct, aureservoir::ESN< T >::getSimAlgorithm, aureservoir::ESN< T >::getTrainAlgorithm, aureservoir::ESN< T >::init, aureservoir::ESN< T >::init_, aureservoir::ESN< T >::init_params_, aureservoir::ESN< T >::inputs_, aureservoir::ESN< T >::net_info_, aureservoir::ESN< T >::neurons_, aureservoir::ESN< T >::noise_, aureservoir::ESN< T >::outputs_, aureservoir::ESN< T >::setInitAlgorithm, aureservoir::ESN< T >::setOutputAct, aureservoir::ESN< T >::setReservoirAct, aureservoir::ESN< T >::setTrainAlgorithm, aureservoir::ESN< T >::sim_, aureservoir::ESN< T >::SIMULATE_ALG, aureservoir::ESN< T >::train, aureservoir::ESN< T >::train_, aureservoir::ESN< T >::W_, aureservoir::ESN< T >::Wback_, aureservoir::ESN< T >::Win_, aureservoir::ESN< T >::Wout_, aureservoir::ESN< T >::x_.
Referenced by aureservoir::ESN< T >::ESN.
aureservoir::ESN< T >::~ESN()
Destructor.
References aureservoir::ESN< T >::init_, aureservoir::ESN< T >::sim_, aureservoir::ESN< T >::train_.
string aureservoir::ESN< T >::getActString(int act)
string of activation function enum
References aureservoir::ACT_LINEAR, aureservoir::ACT_SIGMOID, aureservoir::ACT_TANH, aureservoir::ACT_TANH2.
Referenced by aureservoir::ESN< T >::post.
string aureservoir::ESN< T >::getInitString(int alg)
string of init algorithm enum
References aureservoir::INIT_STD.
Referenced by aureservoir::ESN< T >::post.
string aureservoir::ESN< T >::getSimString(int alg)
string of simulation algorithm enum
References aureservoir::SIM_BP, aureservoir::SIM_FILTER, aureservoir::SIM_FILTER2, aureservoir::SIM_FILTER_DS, aureservoir::SIM_LI, aureservoir::SIM_SQUARE, aureservoir::SIM_STD.
Referenced by aureservoir::ESN< T >::post.
string aureservoir::ESN< T >::getTrainString(int alg)
string of training algorithm enum
References aureservoir::TRAIN_DS_PI, aureservoir::TRAIN_LS, aureservoir::TRAIN_PI, aureservoir::TRAIN_RIDGEREG.
Referenced by aureservoir::ESN< T >::post.